### ISSUE TITLE
Add support for systemd timers instead of cron

### ISSUE THREAD

**Issue by apollo13** [clutterbox/ansible-dehydrated#2]
Hi, would you be open to support systemd timers instead of cron? If yes I'll prepare a PR for it.

**Comment by apollo13** [comment]
With `instead of ` I actually ment `in addition to`

**Comment by azielke** [comment]
Yes, using cron was just a quick solution, which is most likely to work on all systems - even older ones.
I'm currently using this role on some legacy Ubuntu 14.04 and even Ubuntu 12.04 systems.

I thought about using the fact ansible_service_mgr - if it is systemd, use systemd-timers - otherwise cron.
